### ISSUE TITLE
"Can't find device with hash" for Dial

### ISSUE THREAD

**Issue by kaedys** [Stationeers-ic/vscode-stationeers-ic10#65]
**Describe the bug**
Use a `l/lb` command on hash `554524804`, which corresponds with the `Dial` in-game.

<img width="799" alt="20230803-214744-d75f58" src="https://github.com/Stationeers-ic/vscode-stationeers-ic10/assets/9020449/2e66b255-d7e4-4b69-9402-59aca5848c8d">

Note that the extension diagnostics flag it as not matching a known hash:

<img width="352" alt="20230803-215023-27d69d" src="https://github.com/Stationeers-ic/vscode-stationeers-ic10/assets/9020449/3c182fec-ff7c-4126-9317-2ef934d9f28f">

Despite the diagnostic, this code line does successfully run as expected in-game, so the diagnostic is the one that's wrong, not the code.

**Expected behavior**
No diagnostic error

**Comment by Traineratwot** [comment]
Since there is no way to get all the devices of their characteristics from the game. This information is generated by the community. You can join us in the [discord](https://discord.gg/KSVjXufkA9)

[here ](https://docs.google.com/spreadsheets/d/11a_KlDoNv-ZDTKXhhw206uO0xge3_6s2BrCYBfZh86w/edit?usp=sharing) is a table for filling

When there is enough change, I will release an update.

**Comment by kaedys** [comment]
I mean, there's literally [a list of them on the wiki](https://stationeers-wiki.com/ItemHash).  It lacks some of the addition information in that spreadsheet, but it's there for at least hash recognition.  But it's fine, I found another plugin instead.
